version: '3.8'

services:
  news-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-app
    ports:
      - "8080:80"
    restart: unless-stopped
    image: news-website:latest

